### ISSUE TITLE
Theme is not working.

### ISSUE THREAD

**Issue by ghost** [Fsoky/SpaceGalaxy#1]
Hi. I just installed your theme, and it's didn't work.
I use Sublime Text 4, and maybe issue with only this version.
![](https://user-images.githubusercontent.com/59331246/128182574-ee43482d-c6c7-48bd-97d0-898d897d7037.png)

**Comment by Fsoky** [comment]
Try install color-scheme "ayu"

**Comment by ghost** [comment]
Fixed.
