### ISSUE TITLE
Bug with theme display

### ISSUE THREAD

**Issue by iMainDay** [Fsoky/SpaceGalaxy#2]
After installing the theme, there is such a picture:
![изображение](https://user-images.githubusercontent.com/84520551/135772470-09c4c54b-f97a-4e39-a19e-c825af4724a4.png)
the colors of the tabs and the directory tree are displayed incorrectly. 
The problem is observed on Ubuntu 20.04 LTS. How to fix?

**Comment by Fsoky** [comment]
*If you have some bugs, try install ayu theme in sublime*
